name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install packages
      run: npm ci
    - name: Build application
      run: npm run build
  
    - name: PrepareReg Names
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV
      
    - name: Docker login
      run: docker login ghcr.io -u jopverhoeven -p ${{ secrets.GITHUB_TOKEN }}
  
    - name: Docker build
      run: docker build -t ghcr.io/${{ env.IMAGE_REPOSITORY }}/personal-page:$GITHUB_SHA -f Dockerfile .;
  
    - name: Docker publish
      run: docker push ghcr.io/${{ env.IMAGE_REPOSITORY }}/personal-page:$GITHUB_SHA
